//! Compiles a [`ResolvedTheme`] into a GTK CSS string.
//!
//! This is plain string generation — no GTK dependency here. `kaze-ui` is
//! responsible for feeding the returned string into a
//! `gtk4::CssProvider::load_from_string` and applying it via
//! `gtk4::style_context_add_provider_for_display`. Keeping that split
//! means this crate's output is a snapshot-testable `String`.

use crate::tokens::{ResolvedScheme, ResolvedTheme};

/// Generate the full application CSS for the given resolved theme.
///
/// Uses GTK CSS `@define-color` for palette values (so widget templates
/// can reference `@accent_color` etc.) plus a handful of custom style
/// classes (`.kaze-sidebar`, `.kaze-tab-row`, `.kaze-glass`) that the UI
/// widgets opt into.
pub fn generate_css(theme: &ResolvedTheme) -> String {
    let (bg, fg, surface, border) = match theme.scheme {
        ResolvedScheme::Light => ("#fafafa", "#1a1a1a", "#ffffff", "#e0e0e0"),
        ResolvedScheme::Dark => ("#141414", "#f0f0f0", "#1e1e1e", "#2c2c2c"),
    };

    let accent = theme.accent.to_css();
    let radius = theme.corner_radius_px;
    let sidebar_width = theme.sidebar_width_px;

    // Blur is expressed as a CSS custom property consumed by widgets that
    // can actually apply it (see architecture doc §6 — GTK CSS blur
    // support is limited, so widgets fall back gracefully when the
    // compositor doesn't cooperate; this variable is the single knob).
    let blur_stddev = theme.blur_amount * 12.0;

    let transition = if theme.animations_enabled {
        "150ms ease-out"
    } else {
        "0ms"
    };

    let compact_padding = if theme.compact_mode { "4px" } else { "8px" };

    format!(
        r#"
/* Generated by kaze-theme. Do not edit by hand — edit settings.toml
   or use the in-app appearance settings instead. */

@define-color kaze_bg {bg};
@define-color kaze_fg {fg};
@define-color kaze_surface {surface};
@define-color kaze_border {border};
@define-color kaze_accent {accent};

window {{
    background-color: @kaze_bg;
    color: @kaze_fg;
}}

.kaze-sidebar {{
    background-color: @kaze_surface;
    border-right: 1px solid @kaze_border;
    min-width: {sidebar_width}px;
    padding: {compact_padding};
    transition: min-width {transition};
}}

.kaze-tab-row {{
    border-radius: {radius}px;
    padding: {compact_padding};
    transition: background-color {transition}, transform {transition};
}}

.kaze-tab-row:hover {{
    background-color: alpha(@kaze_accent, 0.12);
}}

.kaze-tab-row.active {{
    background-color: alpha(@kaze_accent, 0.20);
}}

.kaze-address-bar {{
    border-radius: {radius}px;
    background-color: @kaze_surface;
    border: 1px solid @kaze_border;
    transition: border-color {transition};
}}

.kaze-address-bar:focus-within {{
    border-color: @kaze_accent;
}}

.kaze-glass {{
    background-color: alpha(@kaze_surface, 0.72);
    /* GTK CSS has no native backdrop-filter; on compositors where
       kaze-ui applies a real blur (via layer-shell hints or a blurred
       snapshot texture), this custom property is what it reads. Where
       unsupported, the alpha-blended surface color above is the
       graceful fallback described in the architecture doc. */
    --kaze-blur-stddev: {blur_stddev}px;
}}

button.suggested-action,
.kaze-accent-bg {{
    background-color: @kaze_accent;
}}

* {{
    outline-color: alpha(@kaze_accent, 0.5);
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tokens::{Rgb, ResolvedScheme, ResolvedTheme};

    fn sample() -> ResolvedTheme {
        ResolvedTheme {
            accent: Rgb { r: 124, g: 108, b: 240 },
            corner_radius_px: 12.0,
            blur_amount: 0.6,
            sidebar_width_px: 240,
            scheme: ResolvedScheme::Dark,
            animations_enabled: true,
            compact_mode: false,
        }
    }

    #[test]
    fn generates_nonempty_css_containing_key_selectors() {
        let css = generate_css(&sample());
        assert!(css.contains(".kaze-sidebar"));
        assert!(css.contains(".kaze-tab-row"));
        assert!(css.contains("@define-color kaze_accent"));
        assert!(css.contains("240px")); // sidebar width made it through
    }

    #[test]
    fn disabling_animations_zeroes_transitions() {
        let mut theme = sample();
        theme.animations_enabled = false;
        let css = generate_css(&theme);
        assert!(css.contains("transition: min-width 0ms"));
    }
}
